### ISSUE TITLE
[feature request] support for ndarrays

### ISSUE THREAD

**Issue by cvanelteren** [andreaferretti/neo#39] opened 2021-05-13 20:51 UTC
Hi, 
I recently came into contact with nim and find it an exciting language. Most of my work heavily relies on numpy and one of its key features is the `ndarray`. Browsing to the tuts and running some code I notice that the support currently is for vectors and 2d matrices only. Is there are road map for `ndarray` support?
Best,
C

**Comment by andreaferretti** [comment] 2021-05-14 07:43
I think this is a duplicate of https://github.com/andreaferretti/neo/issues/11

As you can see, the issue is quite old, and I don't think I am going to work on it soon. Neo was born as an experiment for a linear algebra library with an interface that resembled the one used in mathematics. It would be nice to add support for multidimensional arrays, but realistically this is not going to happen soon.

But you are not out of luck! There are far more advanced (and up to date) libraries for Nim today! You can have a look at [Arraymancer](https://github.com/mratsim/Arraymancer) if you want a pure Nim solution, or [Flambeau](https://github.com/SciNim/flambeau) if you want to wrap PyTorch

**Closed as completed by andreaferretti** 2021-05-14 07:43 UTC

**Comment by cvanelteren** [comment] 2021-05-15 14:03
Thanks for the reply! I will have a look at the resources.
